apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-config
  namespace: drone
data:

  #######################
  # Drone Server Config #
  #######################

  # server host name
  server.host: "http://a25b29a029a2e11e891d4022f25edb64-1076210333.ap-northeast-2.elb.amazonaws.com"
  # start the server in debug mode
  server.debug: "true"
  # open user registration
  server.open: "true"
  # database driver, defaul as sqlite3
  server.database.driver: sqlite3
  # database driver configuration string
  server.database.datasource: drone.sqlite
  # list of admin users
  server.admin: appleboy

  # remote parameters (GitHub)
  server.remote.github: "true"
  server.remote.github.client: b50a70b0f0d4d218895b
  server.remote.github.secret: 3afdc41acb5c05a4e0f4146c97c64e78cd2608da

  # remote parameters (Gitea)
  server.remote.gitea: "false"
  server.remote.gitea.url: "https://try.gitea.io"
  server.remote.gitea.skip.verify: "true"

  ######################
  # Drone Agent Config #
  ######################

  agent.debug: "true"
  agent.debug.pretty: "true"
  agent.max.procs: "1"
  agent.healthcheck: "true"
